version: '3.7'

networks:
  gis-net:
    driver: bridge

services:

  test:
    image: ghcr.io/datakaveri/gis-test:latest
    environment:
      - RS_URL=https://rs.iudx.org.in
      - LOG_LEVEL=INFO
      - GIS_JAVA_OPTS=-Xmx1024m
    volumes:
      - /home/ubuntu/configs/4.5.0/gis-config-test.json:/usr/share/app/configs/config-test.json
      - /home/ubuntu/configs/4.5.0/keystore-gis.jks:/usr/share/app/configs/keystore.jks
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ./src/:/usr/share/app/src
      - ${WORKSPACE}:/tmp/test
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "docker/runTests.sh"

  integTest:
    image: ghcr.io/datakaveri/gis-depl:latest
    environment:
      - RS_URL=https://rs.iudx.org.in
      - LOG_LEVEL=INFO
      - GIS_JAVA_OPTS=-Xmx1024m
    volumes:
      - /home/ubuntu/configs/4.5.0/gis-config-test.json:/usr/share/app/configs/config.json
      - /home/ubuntu/configs/4.5.0/keystore-gis.jks:/usr/share/app/configs/keystore.jks
    ports:
      - "8443:8443"
    networks: 
      - gis-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java $$GIS_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"
    depends_on:
      - "zookeeper"

  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - gis-net